<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

declare(strict_types=1);

namespace core_reportbuilder\local\report;

use core\output\pix_icon;
use core\url;
use lang_string;
use stdClass;

/**
 * Class to represent a report action whose URL is generated by Moodle's Router.
 *
 * @package     core_reportbuilder
 * @copyright   Andrew Lyons <andrew@nicols.co.uk>
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
final class routed_action extends row_action {
    /** @var array|callable|string */
    protected mixed $callable;

    /**
     * Create an instance of an action to be added to a report.
     *
     * @param array|callable|string $callable The callable which identifies the routed path
     * @param pix_icon $icon
     * @param string[] $attributes Array of attributes to include in action, each will be cast to string prior to use
     * @param bool $popup
     * @param ?lang_string $title
     */
    public function __construct(
        /** @var array|callable|string $callable */
        array|callable|string $callable,
        pix_icon $icon,
        array $attributes = [],
        bool $popup = false,
        ?lang_string $title = null
    ) {
        $this->callable = $callable;
        parent::__construct(
            $icon,
            $attributes,
            $popup,
            $title,
        );
    }

    #[\Override]
    protected function get_action_url(stdClass $row): url {
        // Create a new URL instance from our callable with this row.
        return \core\router\util::get_path_for_callable($this->callable, (array) $row);
    }
}
