<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace core\router\response;

use core\param;
use core\router\schema\objects\scalar_type;
use core\router\schema\objects\schema_object;
use core\router\schema\objects\stacktrace;
use core\router\schema\referenced_object;
use core\router\schema\response\content\payload_response_type;
use core\router\schema\response\payload_response;
use GuzzleHttp\Psr7\Response;
use Psr\Http\Message\ServerRequestInterface;

/**
 * A standard response for user preferences.
 *
 * @package    core
 * @copyright  2023 Andrew Lyons <andrew@nicols.co.uk>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
abstract class exception_response extends \core\router\schema\response\response implements
    referenced_object
{
    /**
     * Constructor for a new exception-related response.
     */
    public function __construct() {
        parent::__construct(
            statuscode: static::get_exception_status_code(),
            description: static::get_response_description(),
            content: new payload_response_type(
                schema: static::get_response_schema(),
            ),
        );
    }

    /**
     * Get the response for the exception.
     *
     * @param ServerRequestInterface $request
     * @param \Exception $exception
     * @param mixed[] ...$extra
     * @return payload_response
     */
    public static function get_response(
        ServerRequestInterface $request,
        \Exception $exception,
        ...$extra,
    ): payload_response {
        $extra['request'] = $request;
        return new payload_response(
            payload: static::get_payload_data($exception, ...$extra),
            request: $request,
            response: new Response(
                status: static::get_exception_status_code(),
                body: $exception->getMessage(),
                reason: explode("\n", $exception->getMessage())[0],
            ),
        );
    }

    /**
     * Get the schema for the response.
     *
     * @return schema_object
     */
    protected static function get_response_schema(): schema_object {
        // This schema, and these descriptions, are defined in RFC-9457.
        // See https://www.rfc-editor.org/info/rfc9457/ for further information.
        return new schema_object(
            content: [
                'type' => new scalar_type(
                    type: param::URL,
                    description: 'A URI reference that identifies the problem type.',
                ),
                'title' => new scalar_type(
                    type: param::RAW,
                    description: 'A short, human-readable summary of the problem type.',
                ),
                'status' => new scalar_type(
                    type: param::INT,
                    description: 'The HTTP status code generated by the origin server for this occurrence of the problem.',
                ),
                'detail' => new scalar_type(
                    type: param::RAW,
                    description: 'A human-readable explanation specific to this occurrence of the problem.',
                ),
                'instance' => new scalar_type(
                    type: param::RAW,
                    description: ' URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.',
                ),
            ],
        );
    }

    /**
     * The status code that this exception should return.
     *
     * @return int
     */
    protected static function get_exception_status_code(): int {
        return 500;
    }

    /**
     * Get the description of this response.
     *
     * @return string
     */
    abstract protected static function get_response_description(): string;

    /**
     * Return a URL that identifies the problem type.
     *
     * See {@link https://www.rfc-editor.org/info/rfc9457/#name-type} for further information on valid values.
     *
     * @return null
     */
    protected static function get_response_type(): ?\core\url {
        return null;
    }

    /**
     * Get the response payload data.
     *
     * @param \Exception $exception
     * @param mixed ...$extra
     * @return array
     */
    protected static function get_payload_data(
        \Exception $exception,
        ...$extra,
    ): array {
        // Data for the API Token Exception should meet RFC 9457.
        $data = [
            'status' => static::get_exception_status_code(),
            'title' => static::get_response_description(),
            'detail' => $exception->getMessage(),
        ];

        if ($exception instanceof \core\exception\moodle_exception && $exception->debuginfo !== null) {
            $data['detail'] = rtrim($data['detail'], '.') . '. ' . $exception->debuginfo;
        }

        $type = static::get_response_type();
        if ($type !== null) {
            $data['type'] = $type->out(false);
        } else {
            // If no type is specified, the RFC requires a value of 'about:blank'.
            $data['type'] = 'about:blank';
        }

        if (array_key_exists('request', $extra)) {
            /** @var ServerRequestInterface */
            $request = $extra['request'];

            $data['instance'] = $request->getUri()->getPath();
        }

        return $data;
    }
}
