<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace core\router\parameters;

use core\param;
use core\router\middleware\idempotency_key_middleware;
use core\router\schema\referenced_object;

/**
 * An optional header allowing a client to supply an Idempotency-Key, so that a retried request
 * can be safely replayed rather than repeating the underlying action.
 *
 * This is added to the OpenAPI documentation of every applicable route centrally by
 * {@see \core\router\schema\specification}, rather than being declared per-route: it is handled
 * generically by {@see idempotency_key_middleware} for every route whose method is one of
 * {@see idempotency_key_middleware::APPLICABLE_METHODS}.
 *
 * @package    core
 * @copyright  Andrew Lyons <andrew@nicols.co.uk>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class header_idempotency_key extends \core\router\schema\parameters\header_object implements referenced_object {
    /**
     * Create a new Idempotency-Key header parameter.
     *
     * @param string $name The name of the header
     * @param mixed ...$extra Additional arguments
     */
    public function __construct(
        string $name = idempotency_key_middleware::HEADER_NAME,
        ...$extra,
    ) {
        $extra['name'] = $name;
        $extra['type'] = param::RAW;
        $extra['required'] = false;
        $extra['description'] = implode(' ', [
            'A unique value, generated by the client, identifying this request.',
            'If a request with this header is retried using the same key (for the same route,',
            'request body, and authenticated user), the original response is replayed rather',
            'than repeating the underlying action.',
            'Requires an authenticated request: an unauthenticated request carrying this header',
            'is rejected with a 400 Bad Request.',
            sprintf('Must be a non-empty string of no more than %d characters.', idempotency_key_middleware::MAX_KEY_LENGTH),
        ]);

        parent::__construct(...$extra);
    }
}
