name: Coverage

on:
  push:
    branches-ignore:
      - main
      - MOODLE_[0-9]+_STABLE
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+*
  workflow_dispatch:
    inputs:
      phpunit_extra_options:
        description: Additional options to apply to PHPUnit
        required: false
        default: ''

env:
  php: 8.4

jobs:
  PHPUnit:
    runs-on: ${{ matrix.os }}
    services:
      exttests:
        image: moodlehq/moodle-exttests
        ports:
          - 8080:80
      redis:
        image: redis
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        include:
          # PostgreSQL builds always run with the highest PHP supported version.
          - os: ubuntu-24.04
            php: 8.4
            db: pgsql

    steps:
      - name: Setting up DB pgsql
        if: ${{ matrix.db == 'pgsql' }}
        uses: m4nu56/postgresql-action@v1
        with:
          postgresql version: 15
          postgresql db: test
          postgresql user: test
          postgresql password: test

      - name: Configuring git vars
        uses: rlespinasse/github-slug-action@v4

      - name: Setting up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          coverage: pcov

      - name: Checking out code from ${{ env.GITHUB_REF_SLUG }}
        uses: actions/checkout@v4

      - name: Setting up PHPUnit
        env:
          dbtype: ${{ matrix.db }}
        run: |
          echo "pathtophp=$(which php)" >> $GITHUB_ENV # Inject installed pathtophp to env. The template config needs it.
          cp .github/workflows/config-template.php config.php
          mkdir ../moodledata
          sudo locale-gen en_AU.UTF-8
          php public/admin/tool/phpunit/cli/init.php --no-composer-self-update

      - name: Ignore cobertura
        run: |
          echo 'coverage' >> .git/info/exclude

      - name: Running PHPUnit tests
        env:
          dbtype: ${{ matrix.db }}
          phpunit_options: ${{ secrets.phpunit_options }}
        run: |
          php \
              -dpcov.enabled=1 \
              -dpcov.files=20000 \
              -dpcov.memory=4294967296 \
              vendor/bin/phpunit $phpunit_options \
              --coverage-cobertura coverage/cobertura.xml \
              --coverage-clover coverage/clover.xml \
              --coverage-text coverage/clover.txt \
              ${{ inputs.phpunit_extra_options }}

      - name: Upload Coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          path: coverage

      - name: Coveralls
        if: ${{ env.COVERALLS_REPO_TOKEN }}
        uses: coverallsapp/github-action@v2
        with:
          file: coverage/clover.xml
