name: Web Installer Testing

on:
  workflow_dispatch:

jobs:
  behat:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.1, 8.3]
    steps:
      - uses: andrewnicols/moodle-test-action@v1
